using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text.RegularExpressions;
using System.Windows.Forms;

namespace Tamga.Models
{
    public static class Iso8583Fields
    {
        public static Dictionary<int, FieldDefinition> Fields = new Dictionary<int, FieldDefinition>
        {
            { 2, new FieldDefinition { FieldNumber = 2, Name = "PAN (Primary Account Number)", Type = FieldType.Numeric, LengthType = LengthType.LLVAR, MaxLength = 19 } },
            { 3, new FieldDefinition { FieldNumber = 3, Name = "Processing Code", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 6 } },
            { 4, new FieldDefinition { FieldNumber = 4, Name = "Amount Transaction", Type = FieldType.Amount, LengthType = LengthType.Fixed, MaxLength = 12 } },
            { 5, new FieldDefinition { FieldNumber = 5, Name = "Amount Settlement", Type = FieldType.Amount, LengthType = LengthType.Fixed, MaxLength = 12  }},
            { 6, new FieldDefinition { FieldNumber = 6, Name = "Amount Cardholder Billing", Type = FieldType.Amount, LengthType = LengthType.Fixed, MaxLength = 12} },
            { 7, new FieldDefinition { FieldNumber = 7, Name = "Transmission Date Time", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 10 } },
            { 8, new FieldDefinition { FieldNumber = 8, Name = "Amount Cardholder Billing Fee", Type = FieldType.Amount, LengthType = LengthType.Fixed, MaxLength = 8 } },
            { 9, new FieldDefinition { FieldNumber = 9, Name = "Conversion Rate Settlement", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 8}},
            { 10, new FieldDefinition { FieldNumber = 10,Name = "Conversion Rate Cardholder Billing", Type = FieldType.Numeric, LengthType = LengthType.Fixed,MaxLength = 8}},
            { 11, new FieldDefinition { FieldNumber = 11, Name = "STAN (System Trace Audit Number)", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 6 } },
            { 12, new FieldDefinition { FieldNumber = 12, Name = "Local Time", Type = FieldType.Time, LengthType = LengthType.Fixed, MaxLength = 6 } },
            { 13, new FieldDefinition { FieldNumber = 13, Name = "Local Date", Type = FieldType.Date, LengthType = LengthType.Fixed, MaxLength = 4 } },
            { 14, new FieldDefinition { FieldNumber = 14, Name = "Expiration Date", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 4 } },
            { 15, new FieldDefinition { FieldNumber = 15, Name = "Settlement Date", Type = FieldType.Date, LengthType = LengthType.Fixed, MaxLength = 4}},
            { 16, new FieldDefinition { FieldNumber = 16, Name = "Currency Conversion Date", Type = FieldType.Date,LengthType = LengthType.Fixed, MaxLength = 4}},
            { 17, new FieldDefinition { FieldNumber = 17, Name = "Capture Date",Type = FieldType.Date,LengthType = LengthType.Fixed,MaxLength = 4}},
            { 18, new FieldDefinition { FieldNumber = 18, Name = "Merchant Type (MCC)",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 4}},
            { 19, new FieldDefinition { FieldNumber = 19, Name = "Acquiring Institution Country Code",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 3}},        
            { 20, new FieldDefinition { FieldNumber = 20, Name = "PAN Extended Country Code", Type = FieldType.Numeric, LengthType = LengthType.Fixed,MaxLength = 3}},
            { 21, new FieldDefinition { FieldNumber = 21, Name = "Forwarding Institution Country Code",Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 3}},
            { 22, new FieldDefinition { FieldNumber = 22, Name = "POS Entry Mode", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 3 } },            
            { 23, new FieldDefinition { FieldNumber = 23, Name = "Card Sequence Number", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 3}},
            { 24, new FieldDefinition { FieldNumber = 24, Name = "Network International ID (NII)", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 3}},
            { 25, new FieldDefinition { FieldNumber = 25, Name = "POS Condition Code", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 2 } },          
            { 26, new FieldDefinition { FieldNumber = 26, Name = "POS PIN Capture Code",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 2}},
            { 27, new FieldDefinition { FieldNumber = 27, Name = "Authorization ID Response Length",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 1}},
            { 28, new FieldDefinition { FieldNumber = 28, Name = "Amount Transaction Fee",Type = FieldType.Amount,LengthType = LengthType.Fixed,MaxLength = 9}},
            { 29, new FieldDefinition { FieldNumber = 29, Name = "Amount Settlement Fee",Type = FieldType.Amount,LengthType = LengthType.Fixed,MaxLength = 9}},
            { 30, new FieldDefinition { FieldNumber = 30, Name = "Amount Transaction Processing Fee",Type = FieldType.Amount,LengthType = LengthType.Fixed,MaxLength = 9}},
            { 31, new FieldDefinition { FieldNumber = 31, Name = "Amount Settlement Processing Fee",Type = FieldType.Amount,LengthType = LengthType.Fixed,MaxLength = 9}},
            { 32, new FieldDefinition { FieldNumber = 32, Name = "Acquiring Institution ID", Type = FieldType.Numeric, LengthType = LengthType.LLVAR, MaxLength = 11 } },
            { 33, new FieldDefinition { FieldNumber = 33, Name = "Forwarding Institution ID Code",Type = FieldType.Numeric,LengthType = LengthType.LLVAR,MaxLength = 11}},
            { 34, new FieldDefinition { FieldNumber = 34, Name = "PAN Extended",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLVAR,MaxLength = 28}},        
            { 35, new FieldDefinition { FieldNumber = 35, Name = "Track 2 Data",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLVAR,MaxLength = 37}},
            { 36, new FieldDefinition { FieldNumber = 36, Name = "Track 3 Data",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 104}},
            { 37, new FieldDefinition { FieldNumber = 37, Name = "RRN (Retrieval Reference Number)", Type = FieldType.AlphaNumeric, LengthType = LengthType.Fixed, MaxLength = 12 } },
            { 38, new FieldDefinition { FieldNumber = 38, Name = "Approval Code", Type = FieldType.AlphaNumeric, LengthType = LengthType.Fixed, MaxLength = 6 } },
            { 39, new FieldDefinition { FieldNumber = 39, Name = "Response Code", Type = FieldType.AlphaNumeric, LengthType = LengthType.Fixed, MaxLength = 2 } },           
            { 40, new FieldDefinition { FieldNumber = 40, Name = "Service Restriction Code",Type = FieldType.AlphaNumeric,LengthType = LengthType.Fixed,MaxLength = 3}},
            { 41, new FieldDefinition { FieldNumber = 41, Name = "Terminal ID", Type = FieldType.AlphaNumeric, LengthType = LengthType.Fixed, MaxLength = 8 } },
            { 42, new FieldDefinition { FieldNumber = 42, Name = "Merchant ID", Type = FieldType.AlphaNumeric, LengthType = LengthType.Fixed, MaxLength = 15 } },
            { 43, new FieldDefinition { FieldNumber = 43, Name = "Card Acceptor Name/Location", Type = FieldType.AlphaNumeric, LengthType = LengthType.Fixed, MaxLength = 40 } },        
            { 44, new FieldDefinition { FieldNumber = 44, Name = "Additional Response Data",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLVAR,MaxLength = 25}},
            { 45, new FieldDefinition { FieldNumber = 45, Name = "Track 1 Data",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLVAR,MaxLength = 76 }},       
            { 46, new FieldDefinition { FieldNumber = 46, Name = "Additional Data ISO",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 999}},        
            { 47, new FieldDefinition { FieldNumber = 47, Name = "Additional Data National",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 999}},
            { 48, new FieldDefinition { FieldNumber = 48, Name = "Additional Data", Type = FieldType.AlphaNumeric, LengthType = LengthType.LLLVAR, MaxLength = 999 } },
            { 49, new FieldDefinition { FieldNumber = 49, Name = "Currency Code", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 3 } },
            { 50, new FieldDefinition { FieldNumber = 50, Name = "Currency Code Settlement",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 3}},
            { 51, new FieldDefinition { FieldNumber = 51, Name = "Currency Code Cardholder Billing",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 3}},
            { 52, new FieldDefinition { FieldNumber = 52, Name = "PIN Data", Type = FieldType.Binary, LengthType = LengthType.Fixed, MaxLength = 16 } },
            { 53, new FieldDefinition { FieldNumber = 53, Name = "Security Related Control Information",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 16}},
            { 54, new FieldDefinition { FieldNumber = 54, Name = "Additional Amounts",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 120}},
            { 55, new FieldDefinition { FieldNumber = 55, Name = "EMV Data", Type = FieldType.Binary, LengthType = LengthType.LLLVAR, MaxLength = 999 } },  
            { 56, new FieldDefinition { FieldNumber = 56, Name = "Reserved ISO",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 999}},
            { 57, new FieldDefinition { FieldNumber = 57, Name = "Reserved National",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 999}},
            { 58, new FieldDefinition { FieldNumber = 58, Name = "Reserved National",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR, MaxLength = 999}},
            { 59, new FieldDefinition { FieldNumber = 59, Name = "Reserved National",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 999}},        
            { 60, new FieldDefinition { FieldNumber = 60, Name = "Reserved National",Type = FieldType.AlphaNumeric,LengthType = LengthType.LLLVAR,MaxLength = 999}},
            { 61, new FieldDefinition { FieldNumber = 61, Name = "Reserved Private", Type = FieldType.AlphaNumeric, LengthType = LengthType.LLLVAR, MaxLength = 999 } },
            { 62, new FieldDefinition { FieldNumber = 62, Name = "Reserved Private", Type = FieldType.AlphaNumeric, LengthType = LengthType.LLLVAR, MaxLength = 999 } },
            { 63, new FieldDefinition { FieldNumber = 63, Name = "Private Data", Type = FieldType.AlphaNumeric, LengthType = LengthType.LLLVAR, MaxLength = 999 } },            
            { 64, new FieldDefinition { FieldNumber = 64, Name = "Message Authentication Code (MAC)",Type = FieldType.Binary,LengthType = LengthType.Fixed,MaxLength = 8}},
            { 65, new FieldDefinition { FieldNumber = 65, Name = "Reserved ISO",Type = FieldType.Binary,LengthType = LengthType.Fixed,MaxLength = 1 }},
            { 66, new FieldDefinition { FieldNumber = 66, Name = "Settlement Code",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 1}},
            { 67, new FieldDefinition { FieldNumber = 67, Name = "Extended Payment Code",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 2}},
            { 68, new FieldDefinition { FieldNumber = 68, Name = "Receiving Institution Country Code",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 3}},
            { 69, new FieldDefinition { FieldNumber = 69, Name = "Settlement Institution Country Code",Type = FieldType.Numeric,LengthType = LengthType.Fixed,MaxLength = 3}},
            { 70, new FieldDefinition { FieldNumber = 70, Name = "Network Management Code", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 3 } },
            { 90, new FieldDefinition { FieldNumber = 90, Name = "Original Data Elements", Type = FieldType.Numeric, LengthType = LengthType.Fixed, MaxLength = 42 } },           
            { 124, new FieldDefinition { FieldNumber = 124, Name = "Info Text", Type = FieldType.AlphaNumeric, LengthType = LengthType.LLLVAR, MaxLength = 255 } },
        };
    }
}